'use strict';

module.exports = {
	'1': {modeloid: 1, modeloname: "CR300", modemcode: 7, modemname: "GE864-QUAD-V2"},
	'2': {modeloid: 2, modeloname: "CFE", modemcode: 0, modemname: "No Modem"},
	'194': {modeloid: 2, modeloname: "PHSN RF Head", modemcode: 6, modemname: "No Modem"},
	'35': {modeloid: 3, modeloname: "Olympic", modemcode: 1, modemname: "No Modem - Tetra/Astro external modem"},
	'4': {modeloid: 4, modeloname: "Compact Fleet", modemcode: 0, modemname: "Sony/Erickson GR47"},
	'36': {modeloid: 4, modeloname: "Compact Fleet", modemcode: 1, modemname: "Enfora Enabler II-G"},
	'68': {modeloid: 4, modeloname: "Compact Fleet", modemcode: 2, modemname: "Telit GE864, old retrofit board(obsolete)"},
	'100': {modeloid: 4, modeloname: "Compact Fleet", modemcode: 3, modemname: "Telit GE864, mute support"},
	'5': {modeloid: 5, modeloname: "Compact Security", modemcode: 0, modemname: "Sony/Erickson GR47"},
	'37': {modeloid: 5, modeloname: "Compact Security", modemcode: 1, modemname: "Enfora Enabler II-G"},
	'69': {modeloid: 5, modeloname: "Compact Security", modemcode: 2, modemname: "Telit GE864, old retrofit board(obsolete)"},
	'101': {modeloid: 5, modeloname: "Compact Security", modemcode: 3, modemname: "Telit GE864, mute support"},
	'39': {modeloid: 7, modeloname: "Compact CAN 8 Sensor", modemcode: 1, modemname: "Enfora Enabler II-G"},
	'71': {modeloid: 7, modeloname: "", modemcode: 2, modemname: "Telit GE864, old retrofit board(obsolete)"},
	'199': {modeloid: 7, modeloname: "Compact CAN TOB", modemcode: 6, modemname: "Telit GE864, automotive"},
	'8': {modeloid: 8, modeloname: "CelloTrack nano 10 (Telit JF2 GPS)", modemcode: 0, modemname: "Cinterion BGS2-W.Rel2"},
	'40': {modeloid: 8, modeloname: "CelloTrack nano 10 (Telit JF2 GPS)", modemcode: 1, modemname: "Cinterion EHS5-E"},
	'72': {modeloid: 8, modeloname: "CelloTrack nano 10 (Telit JF2 GPS)", modemcode: 2, modemname: "Cinterion EHS5-US"},
	'136': {modeloid: 8, modeloname: "CelloTrack nano 10 (Telit SE868-V2 GNSS)", modemcode: 4, modemname: "Cinterion BGS2-W.Rel2"},
	'168': {modeloid: 8, modeloname: "CelloTrack nano 10 (Telit SE868-V2 GNSS)", modemcode: 5, modemname: "Cinterion EHS5-E"},
	'200': {modeloid: 8, modeloname: "CelloTrack nano 10 (Telit SE868-V2 GNSS)", modemcode: 6, modemname: "Cinterion EHS5-US"},
	'9': {modeloid: 9, modeloname: "370-50", modemcode: 0, modemname: "Sony/Erickson GR47"},
	'105': {modeloid: 9, modeloname: "370-50", modemcode: 3, modemname: "Telit GE864, mute support"},
	'170': {modeloid: 10, modeloname: "CelloTrack 1 Output", modemcode: 5, modemname: "Enfora 3"},
	'235': {modeloid: 11, modeloname: "CR300B", modemcode: 7, modemname: "GE864-QUAD-V2"},
	'172': {modeloid: 12, modeloname: "CelloTrack", modemcode: 5, modemname: "Enfora III"},
	'78': {modeloid: 14, modeloname: "Cello-IQ GNSS", modemcode: 2, modemname: "GE910 QUAD V3"},
	'209': {modeloid: 17, modeloname: "Compact CAN TOB", modemcode: 6, modemname: "Telit GE864, automotive"},
	'18': {modeloid: 18, modeloname: "CelloTrack T (2G)", modemcode: 0, modemname: "Telit GE910 QUAD (v2) (V3)"},
	'82': {modeloid: 18, modeloname: "CelloTrack T (3G)", modemcode: 2, modemname: "Telit HE910 NAD"},
	'19': {modeloid: 19, modeloname: "CelloTrackPower T (2G)", modemcode: 0, modemname: "Telit GE910 QUAD (v2) (V3)"},
	'83': {modeloid: 19, modeloname: "CelloTrackPower T (3G)", modemcode: 2, modemname: "Telit HE910 NAD"},
	'20': {modeloid: 20, modeloname: "Cello-CANiQ (NA)", modemcode: 0, modemname: "UE910 NAR"},
	'52': {modeloid: 20, modeloname: "Cello-CANiQ (EU)", modemcode: 1, modemname: "UE910 EUR"},
	'84': {modeloid: 20, modeloname: "Cello-CANiQ (2G)", modemcode: 2, modemname: "GE910 QUAD V3"},
	'182': {modeloid: 22, modeloname: "compact EOB", modemcode: 5, modemname: "Enfora III"},
	'183': {modeloid: 23, modeloname: "CelloTrack Power", modemcode: 5, modemname: "Enfora III"},
	'216': {modeloid: 24, modeloname: "Cello (Telit)", modemcode: 6, modemname: "Telit GE864, automotive"},
	'249': {modeloid: 25, modeloname: "Cello Cinterion", modemcode: 7, modemname: "Cinterion BGS3"},
	'26': {modeloid: 26, modeloname: "Cello Cinterion", modemcode: 0, modemname: "Cinterion BGS2-W.Rel2"},
	'58': {modeloid: 26, modeloname: "CelloTrack nano 20 (Telit SE868-V2 GNSS)", modemcode: 1, modemname: "Cinterion EHS5-E"},
	'90': {modeloid: 26, modeloname: "CelloTrack nano 20 (Telit SE868-V2 GNSS)", modemcode: 2, modemname: "Cinterion EHS5-US"},
	'122': {modeloid: 26, modeloname: "CelloTrack nano 20 (Telit SE868-V2 GNSS)", modemcode: 3, modemname: "Cinterion EHS6"},
	'154': {modeloid: 26, modeloname: "CelloTrack nano 20 (Telit JF2 GPS)", modemcode: 4, modemname: "Cinterion BGS2-W.Rel2"},
	'186': {modeloid: 26, modeloname: "CelloTrack nano 20 (Telit JF2 GPS)", modemcode: 5, modemname: "Cinterion EHS5-E"},
	'218': {modeloid: 26, modeloname: "CelloTrack nano 20 (Telit JF2 GPS)", modemcode: 6, modemname: "Cinterion EHS5-US"},
	'250': {modeloid: 26, modeloname: "CelloTrack nano 20 (Telit JF2 GPS)", modemcode: 7, modemname: "Cinterion EHS6"},
	'220': {modeloid: 28, modeloname: "(Compact (TOB)) in use", modemcode: 6, modemname: "Telit GE864, automative"},
	'221': {modeloid: 29, modeloname: "CR200", modemcode: 6, modemname: "Telit GE864, automative"},
	'223': {modeloid: 30, modeloname: "CR200B", modemcode: 6, modemname: "Telit GE864, automative"},
	'224': {modeloid: 31, modeloname: "Cello-IQ", modemcode: 6, modemname: "Telit GE864, automative"}
}
