'use strict';

module.exports = {
	'1': {modeloId: 1, modeloName: "CR300", modemCode: 7, modemName: "GE864-QUAD-V2"},
	'2': {modeloId: 2, modeloName: "CFE", modemCode: 0, modemName: "No Modem"},
	'194': {modeloId: 2, modeloName: "PHSN RF Head", modemCode: 6, modemName: "No Modem"},
	'35': {modeloId: 3, modeloName: "Olympic", modemCode: 1, modemName: "No Modem - Tetra/Astro external modem"},
	'4': {modeloId: 4, modeloName: "Compact Fleet", modemCode: 0, modemName: "Sony/Erickson GR47"},
	'36': {modeloId: 4, modeloName: "Compact Fleet", modemCode: 1, modemName: "Enfora Enabler II-G"},
	'68': {modeloId: 4, modeloName: "Compact Fleet", modemCode: 2, modemName: "Telit GE864, old retrofit board(obsolete)"},
	'100': {modeloId: 4, modeloName: "Compact Fleet", modemCode: 3, modemName: "Telit GE864, mute support"},
	'5': {modeloId: 5, modeloName: "Compact Security", modemCode: 0, modemName: "Sony/Erickson GR47"},
	'37': {modeloId: 5, modeloName: "Compact Security", modemCode: 1, modemName: "Enfora Enabler II-G"},
	'69': {modeloId: 5, modeloName: "Compact Security", modemCode: 2, modemName: "Telit GE864, old retrofit board(obsolete)"},
	'101': {modeloId: 5, modeloName: "Compact Security", modemCode: 3, modemName: "Telit GE864, mute support"},
	'39': {modeloId: 7, modeloName: "Compact CAN 8 Sensor", modemCode: 1, modemName: "Enfora Enabler II-G"},
	'71': {modeloId: 7, modeloName: "", modemCode: 2, modemName: "Telit GE864, old retrofit board(obsolete)"},
	'199': {modeloId: 7, modeloName: "Compact CAN TOB", modemCode: 6, modemName: "Telit GE864, automotive"},
	'8': {modeloId: 8, modeloName: "CelloTrack nano 10 (Telit JF2 GPS)", modemCode: 0, modemName: "Cinterion BGS2-W.Rel2"},
	'40': {modeloId: 8, modeloName: "CelloTrack nano 10 (Telit JF2 GPS)", modemCode: 1, modemName: "Cinterion EHS5-E"},
	'72': {modeloId: 8, modeloName: "CelloTrack nano 10 (Telit JF2 GPS)", modemCode: 2, modemName: "Cinterion EHS5-US"},
	'136': {modeloId: 8, modeloName: "CelloTrack nano 10 (Telit SE868-V2 GNSS)", modemCode: 4, modemName: "Cinterion BGS2-W.Rel2"},
	'168': {modeloId: 8, modeloName: "CelloTrack nano 10 (Telit SE868-V2 GNSS)", modemCode: 5, modemName: "Cinterion EHS5-E"},
	'200': {modeloId: 8, modeloName: "CelloTrack nano 10 (Telit SE868-V2 GNSS)", modemCode: 6, modemName: "Cinterion EHS5-US"},
	'9': {modeloId: 9, modeloName: "370-50", modemCode: 0, modemName: "Sony/Erickson GR47"},
	'105': {modeloId: 9, modeloName: "370-50", modemCode: 3, modemName: "Telit GE864, mute support"},
	'170': {modeloId: 10, modeloName: "CelloTrack 1 Output", modemCode: 5, modemName: "Enfora 3"},
	'235': {modeloId: 11, modeloName: "CR300B", modemCode: 7, modemName: "GE864-QUAD-V2"},
	'172': {modeloId: 12, modeloName: "CelloTrack", modemCode: 5, modemName: "Enfora III"},
	'78': {modeloId: 14, modeloName: "Cello-IQ GNSS", modemCode: 2, modemName: "GE910 QUAD V3"},
	'209': {modeloId: 17, modeloName: "Compact CAN TOB", modemCode: 6, modemName: "Telit GE864, automotive"},
	'18': {modeloId: 18, modeloName: "CelloTrack T (2G)", modemCode: 0, modemName: "Telit GE910 QUAD (v2) (V3)"},
	'82': {modeloId: 18, modeloName: "CelloTrack T (3G)", modemCode: 2, modemName: "Telit HE910 NAD"},
	'19': {modeloId: 19, modeloName: "CelloTrackPower T (2G)", modemCode: 0, modemName: "Telit GE910 QUAD (v2) (V3)"},
	'83': {modeloId: 19, modeloName: "CelloTrackPower T (3G)", modemCode: 2, modemName: "Telit HE910 NAD"},
	'20': {modeloId: 20, modeloName: "Cello-CANiQ (NA)", modemCode: 0, modemName: "UE910 NAR"},
	'52': {modeloId: 20, modeloName: "Cello-CANiQ (EU)", modemCode: 1, modemName: "UE910 EUR"},
	'84': {modeloId: 20, modeloName: "Cello-CANiQ (2G)", modemCode: 2, modemName: "GE910 QUAD V3"},
	'182': {modeloId: 22, modeloName: "compact EOB", modemCode: 5, modemName: "Enfora III"},
	'183': {modeloId: 23, modeloName: "CelloTrack Power", modemCode: 5, modemName: "Enfora III"},
	'216': {modeloId: 24, modeloName: "Cello (Telit)", modemCode: 6, modemName: "Telit GE864, automotive"},
	'249': {modeloId: 25, modeloName: "Cello Cinterion", modemCode: 7, modemName: "Cinterion BGS3"},
	'26': {modeloId: 26, modeloName: "Cello Cinterion", modemCode: 0, modemName: "Cinterion BGS2-W.Rel2"},
	'58': {modeloId: 26, modeloName: "CelloTrack nano 20 (Telit SE868-V2 GNSS)", modemCode: 1, modemName: "Cinterion EHS5-E"},
	'90': {modeloId: 26, modeloName: "CelloTrack nano 20 (Telit SE868-V2 GNSS)", modemCode: 2, modemName: "Cinterion EHS5-US"},
	'122': {modeloId: 26, modeloName: "CelloTrack nano 20 (Telit SE868-V2 GNSS)", modemCode: 3, modemName: "Cinterion EHS6"},
	'154': {modeloId: 26, modeloName: "CelloTrack nano 20 (Telit JF2 GPS)", modemCode: 4, modemName: "Cinterion BGS2-W.Rel2"},
	'186': {modeloId: 26, modeloName: "CelloTrack nano 20 (Telit JF2 GPS)", modemCode: 5, modemName: "Cinterion EHS5-E"},
	'218': {modeloId: 26, modeloName: "CelloTrack nano 20 (Telit JF2 GPS)", modemCode: 6, modemName: "Cinterion EHS5-US"},
	'250': {modeloId: 26, modeloName: "CelloTrack nano 20 (Telit JF2 GPS)", modemCode: 7, modemName: "Cinterion EHS6"},
	'220': {modeloId: 28, modeloName: "(Compact (TOB)) in use", modemCode: 6, modemName: "Telit GE864, automative"},
	'221': {modeloId: 29, modeloName: "CR200", modemCode: 6, modemName: "Telit GE864, automative"},
	'223': {modeloId: 30, modeloName: "CR200B", modemCode: 6, modemName: "Telit GE864, automative"},
	'224': {modeloId: 31, modeloName: "Cello-IQ", modemCode: 6, modemName: "Telit GE864, automative"}
}
